### ISSUE TITLE
It won't work

### ISSUE THREAD

**Issue by feriousdesteny** [Herysia/CustomKeyBinds#4]
I've done everything i was supposed to do and it didn't work, I have put the files from 2019.4.9.zip into /BepInEx/unhollowed/base and that didn't work. It just opened and then closed and then opened back up in normal Among Us and nothing changed. Ive tried it with the sheriff mod too and it just glitched and i couldn't do anything. Please tell me if I did something wrong or how i can fix this.

Thank you.

**Comment by Herysia** [comment]
I suggest you to either reinstall among us or delete BepInEx folder, and then follow the installation steps again, using the zip file in the release (everything is included in it)

**Comment by feriousdesteny** [comment]
ok thank you
