### ISSUE TITLE
Can't use keys that can be rebound after updating to latest version

### ISSUE THREAD

**Issue by Ten0** [Herysia/CustomKeyBinds#7]
I'm using Among Us 2021.3.31.3s, and with the mod installed, I get the additional bindings menu in the settings, but none of them work in game: I can't move. (Nor the default nor the overridden bindings work).

**Comment by Herysia** [comment]
Hi, someone has reported it already. I'm trying to troubleshoot as it is working for me. Can you please tell me if you installed using the zip folder ?

**Comment by Herysia** [comment]
[CustomKeybinds-2021.3.31s.zip](https://github.com/Herysia/CustomKeyBinds/files/6251097/CustomKeybinds-2021.3.31s.zip)
Can you try deleting mono and bepinex folder and replace them with those ?

**Comment by Herysia** [comment]
Apparently there has been an update that my steam didn't grabbed for some reasons, all the obfuscated names are wrong. I'm going to update it asap

**Comment by Herysia** [comment]
I have updated it in the latest release, i'll not close this issue until it's working :)
